[phases.setup]
nixPkgs = ["python311", "playwright-driver-chromium"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --no-input",
    "python manage.py migrate"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

